sudo: false
env:
    # LEGIFRANCE_PROXY
    - secure: gIgKezNmSCdorAJsX4k1o2c7KqBWspFNmULAQx4fcTUFLomUoNiQjB1R6dDCNcma1ImM9lo3h10s8xsd50guta2iorARZswbe5WqMY3LycyK1Q7/ttxpohQb0ou0hSHNeooaXLeWJi0WqKX+3U1sZbn9TVsFYLY3xO5m1LVyqZx9l4GqwHb7WfSmd1PdcNZbb+sGKSxJX9CpSbz+VPTHvY81dEx2/wVYCMlv5bUOFKDb3oFr7cUyZsYlT9LAfCwYAa0hjbZEK/gRxWON/saG5nJVwLOHCXJi1dJxW1K94jfw9dAfH8EeF1Y/6IFlyrC3Y9Rj1A8csMjSnEMn9lxrewyZY8DieLQvFIdtf5CtzqhCERmXYn30U2WH1ADQloyl45ZCMKBKy8mZiOfPHvgF+iHRrPuatZl+zSqtxrGHcZc6u2wUTOldtMdO/aUdzxlfWfJxEVsS8HbTHWg9kpcU0ReLKQBwi/Z8YKxrbzDljM9k+umXcmMGLZm2AtG0AZQvAm+GVxhjbRrXcaTEEFiLyZGRpf44eeRel+do/ZRGJI/GDSsMRLPVycx9/o/ysRfNADEEVju4Gkj86NYTZD6lKQm5EQACbISFhorayaYHy6ilzEMnf0kte1Z6z7wQGyHF2XSOCLq1FodbTaJuD4Bo7/RRbW95JHkPhpYrlh8uPCs=
language: python
python:
    - "3.4"
    - "3.5"
    - "3.6"
install: pip install -r test_requirements.txt
script: pytest --cov=senapy -s # don't capture output to avoid timeout
after_success: coveralls
